### ISSUE TITLE
Converting  XML-string (not file) scrambles utf-8 characters

### ISSUE THREAD

**Issue by cfmes** [nashwaan/xml-js#110]
```
var convert = require('xml-js');
var xml =
'<?xml version="1.0" encoding="utf-8"?>' +
'<note importance="high" logged="true">' +
'    <title>Deutsche TODOs</title>' +
'    <todo>Ihr seid schön!</todo>' +
'    <todo>Schönen abend sagen zur meine Frau!</todo>' +
'</note>';
var result1 = convert.xml2json(xml, {compact: true, spaces: 4});
console.log(result1, '\n', result1);
```

**Result1**
It simply scrambles the text with umlauts inside the `<todo>` tags:

```
{
    "_declaration": {
        "_attributes": {
            "version": "1.0",
            "encoding": "utf-8"
        }
    },
    "note": {
        "_attributes": {
            "importance": "high",
            "logged": "true"
        },
        "title": {
            "_text": "Deutsche TODOs"
        },
        "todo": [
            {
                "_text": "Ihr seid schÃ¶n!"
            },
            {
                "_text": "SchÃ¶nen abend sagen zur meine Frau!"
            }
        ]
    }
}
```

Got any solution for this?

Regards
Emdadul

**Comment by cfmes** [comment]
[My question on SO](https://stackoverflow.com/questions/56868940/xml-js-package-converting-xml-string-not-file-to-js-scrambles-utf-8-charcaters)

**Comment by Anticom** [comment]
Can not reproduce: https://runkit.com/anticom/5d1ca4978e5953001a963b81

**Comment by cfmes** [comment]
> Can not reproduce: https://runkit.com/anticom/5d1ca4978e5953001a963b81

I think because you have used an updated version of `xml-js`  `var convert = require('xml-js', '1.6.11' );`

Could do that as well but not sure about the side effects. Will try though :)

**Comment by cfmes** [comment]
This is damp squib, was actually a Powershell issue that showed me scrambled characters. In database it looks quite okay after insertion.

**Comment by cfmes** [comment]
This is damp squib, was actually a Powershell issue that showed me scrambled characters. In database it looks quite okay after insertion.
