### ISSUE TITLE
js2xml outputs empty string

### ISSUE THREAD

**Issue by jncr** [nashwaan/xml-js#20]
```
// test.js
const convert = require('xml-js');
const js = { request: { user: 'username', pass: 'password', numbers: { number: 1, number: 2 } } }
const xml = convert.js2xml(js);
console.log(xml);
```
``` 
> node test.js
''
```

node@8.1.2
xml-js@1.3.2

runkit here - https://runkit.com/jncr/xml-js. Something I'm doing wrong?

**Comment by nashwaan** [comment]
@jncr ,
First of all, your js object is illegal. The `numbers` object has two properties of same name, `number`.
Secondly, the js object is missing `_text` property.

The correct js object should be:
```js
const js = {
    request: {
        user: {
            _text: 'username'
        },
        pass: {
            _text: 'password'
        },
        numbers: {
            number: [
                {
                    _text: 1
                },
                {
                    _text: 2
                }
            ]
        }
    }
};
```
Lastly, you need to pass `compact: true` option to tell the parser that the input is in compact form:
```js
const xml = convert.js2xml(js, {compact: true});
```
------
However, your sample input is simpler and I like it. I will try to add support to this kind of input so the parser can accept the following (note the usage of array in `number` to work around javascript object restriction):
```js
const js = {
  request: {
    user: 'username', 
    pass: 'password', 
      numbers: {
        number: [1, 2]
      }
    }
  }
}
```

**Comment by nashwaan** [comment]
Sorry @jncr. Now I remember why I did not support this kind of input. Although input like 
```js
const js = {name: 'Yousuf'}
```
is simpler than:
```js
const js = {name: {_text: 'Yousuf'}}
```
which both can be parsed into xml as:
```xml
<name>Yousuf</name>
```
-----
But the problem occurs when there is some attributes with the node. Say we want the output xml to be:
```xml
<name title="Mr">Yousuf</name>
```
We cannot use your syntax to support this. But we can use this syntax to support this requirement:
```js
const js = {name: {_attributes: {title: 'Mr'}, _text: 'Yousuf'}}
```
-----
To further illustrate why `_text_` is crucial, consider the following example:
```js
const js = {name: {_attributes: {title: 'Mr'}, _text: 'Yousuf', rating: {_text: 'good'}}}
```
which will generate following xml:
```xml
<name title="Mr">
    Yousuf
    <rating>good</rating>
</name>
```
I don't think this can be represented by your js object syntax.

**Comment by nashwaan** [comment]
@jncr 
I have supported in `v1.5.1` converting js object `{a: 'hi'}` (rather than `{a: {_text: 'hi'}}`) to `<a>hi</a>`.

See also [release notes](https://github.com/nashwaan/xml-js/releases/tag/1.5.1).
