### ISSUE TITLE
Declaration parsing is wrong.

### ISSUE THREAD

**Issue by SergeyFromHell** [nashwaan/xml-js#25]
If you use .xml2js (not .xml2json!) function with an XML file that contain following declaration:
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>`
you get wrong declaration attributes (there will be extra attribute with name 'undefined' and value undefined).
In my debuging I found that the following code in lib/xml2js.js is producing that wrong result.
The reason is wrong RegExp used to parse next attribute name and value:
`/([\w:-]+)\s*=\s*"([^"]*)"|'([^']*)'|(\w+)\s*/`
The | (boolean OR) has priority so that regexp actually accepts (key=(spaces)"value") OR ('value') OR (value(spaces)).
The working regexp is, for example:
`/([\w:-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\w+))\s*/`
Code with wrong regexp (lib\xml2js.js):
`    if (instruction.body && (instruction.name.toLowerCase() === 'xml' || options.instructionHasAttributes)) {
        while (instruction.body) {
            var attribute = instruction.body.match(/([\w:-]+)\s*=\s*"([^"]*)"|'([^']*)'|(\w+)\s*/);
            if (!attribute) {
                break;
            }
            attributes[attribute[1]] = attribute[2];
            instruction.body = instruction.body.slice(attribute[0].length); // advance the string
        }
    }`

**Comment by nashwaan** [comment]
@SergeyFromHell Your suggested regex has been incorporated in v1.3.4.
