### ISSUE TITLE
.replace undefined for numbers

### ISSUE THREAD

**Issue by mariotsi** [nashwaan/xml-js#28]
If the attribute is a number `attributes[key].replace is not a function` is fired fired. 
https://github.com/nashwaan/xml-js/blob/ea8857790cba0ba5aa2c071452553531d9300f65/lib/js2xml.js#L45

Test https://runkit.com/embed/3b2200qxgkv4

**Comment by nashwaan** [comment]
@mariotsi  I have published v1.4.1 to address this issue.
Does it work for you now?

**Comment by mariotsi** [comment]
I was preparing a pull request with a toString() as solution. However works fine, thanks for the rapidity.
