### ISSUE TITLE
Error: Text data outside of root node

### ISSUE THREAD

**Issue by MarkPareja** [nashwaan/xml-js#3]
XML - > 
`<?xml version="1.0" encoding="utf-8"?>`
`<dp:ListServicesReply ReturnCode="0" xmlns:dp="http://www.cisco.com/vtg/diagnosticportal">`
`<dp:Schema Version="1.0" />`
`    <dp:ServiceList>`
`        <dp:Service Name="Cisco ICM usgd1 LoggerA" Description="Provides Call Logging services for Instance usgd1" Status="Running" StartupType="Auto" LogOnAs="****" />`
`        <dp:Service Name="Cisco ICM Diagnostic Framework" Description="Provides a web-based diagnostic service for Cisco Unified ICM, Contact Center Enterprise application." Status="Running" StartupType="Auto" LogOnAs="LocalSystem" />`
`     </dp:ServiceList>`
`</dp:ListServicesReply>`

Getting this stack when attempting to parse the above XML doc 

/node_modules/sax/lib/sax.js:984

      throw this.error
      ^

Error: Text data outside of root node.
Line: 0
Column: 15
Char: ]

at error (./node_modules/sax/lib/sax.js:667:10)
    at strictFail (./node_modules/sax/lib/sax.js:693:7)
    at Object.write (./node_modules/sax/lib/sax.js:1048:15)
    at module.exports (./node_modules/xml-js/lib/xml2js.js:226:16)
    at Object.module.exports [as xml2json] (./node_modules/xml-js/lib/xml2json.js:15:10)
    at Object.<anonymous> (./portico.js:27:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

**Comment by nashwaan** [comment]
Sorry @MarkPareja, I could not reproduce the problem. Can you explain how did you attempt to initiate the conversion?

This is what I did and worked well for me:
I saved your xml content in a file `pareja.xml`.
Then I wrote the following code:
```
var convert = require('xml-js');
var xml = require('fs').readFileSync('pareja.xml', 'utf8');
var result = convert.xml2json(xml, {compact: true, spaces: 4});
console.log(result);
```
which produced the following correct result:
```
{
    "_declaration": {
        "_attributes": {
            "version": "1.0",
            "encoding": "utf-8"
        }
    },
    "dp:ListServicesReply": {
        "_attributes": {
            "ReturnCode": "0",
            "xmlns:dp": "http://www.cisco.com/vtg/diagnosticportal"
        },
        "dp:Schema": {
            "_attributes": {
                "Version": "1.0"
            }
        },
        "dp:ServiceList": {
            "dp:Service": [
                {
                    "_attributes": {
                        "Name": "Cisco ICM usgd1 LoggerA",
                        "Description": "Provides Call Logging services for Instance usgd1",
                        "Status": "Running",
                        "StartupType": "Auto",
                        "LogOnAs": "****"
                    }
                },
                {
                    "_attributes": {
                        "Name": "Cisco ICM Diagnostic Framework",
                        "Description": "Provides a web-based diagnostic service for Cisco Unified ICM, Contact Center Enterprise application.",
                        "Status": "Running",
                        "StartupType": "Auto",
                        "LogOnAs": "LocalSystem"
                    }
                }
            ]
        }
    }
}
```
I also tried with `compact: false` and worked without issues.

I tried converting using command line (when installing the library globally as `npm install --global xml-js`) and then typing the following command in the prompt:
`xml-js pareja.xml --compact --spaces 4` and that also worked without issues.

So, can you help me to reproduce the error that you are facing.

**Comment by MarkPareja** [comment]
Thank you, 
I found the issue was with the parent lib, using native http module resolved it, thank you for looking into it.

**Comment by ietuday** [comment]
I Also getting Same Issue.

/home/oit/MyProjects/xmlConversion/node_modules/sax/lib/sax.js:968
      throw this.error
      ^

Error: Text data outside of root node.
Line: 145786
Column: 1
Char: 

Please any one help me. Thanks in Advance
