### ISSUE TITLE
XML declaration with attributes using single quotes

### ISSUE THREAD

**Issue by nunocastromartins** [nashwaan/xml-js#34]
When using `xml2js`, this XML declaration is detected:
```xml
<?xml version="1.0" encoding="UTF-8"?>
```
Whilst this one, which I believe is legal, is not detected:
```xml
<?xml version='1.0' encoding='UTF-8'?>
```

Thank you for your good work!

**Comment by nashwaan** [comment]
While this xml is legal `<?xml version='1.0' encoding='UTF-8'?>`, unfortunately, the underlying [sax](https://github.com/isaacs/sax-js) parser which this library is depending on, doesn't seem to support single quotes attribute values.

Therefore, I suggest you try to do manual cleanup (by converting single quotes to double quotes) before passing the xml input to this library.

**Comment by nunocastromartins** [comment]
Actually, I think this is on you; from reading through sax's source, it seems to support single quotes, it just doesn't parse instructions.

You're the one doing the parsing inside this function: https://github.com/nashwaan/xml-js/blob/master/lib/xml2js.js#L96.

Your regular expression is likely the issue, I'll give it a look.

**Comment by nashwaan** [comment]
Yes, you are right. This part of parsing is done by this library not sax.
🤦

I feel there is something wrong with this line https://github.com/nashwaan/xml-js/blob/master/lib/xml2js.js#L100 
I need to investigate this.

**Comment by nunocastromartins** [comment]
The regexp itself seems correct, but you're doing the parsing in a bit of a silly manner, I think!
I'd likely set the global `g` flag on the regexp and iterate the resulting array after calling `match`.

**Comment by nashwaan** [comment]
> you're doing the parsing in a bit of a silly manner

😄

Would appreciate if you can submit a pull request.

**Comment by nunocastromartins** [comment]
Ah, I didn't mean to offend!

Either way, I'll give it a go in a bit. :-)

**Comment by nashwaan** [comment]
No not at all. I didn't feel offended by this. I just liked the way you phrased it and laughed.

**Comment by nunocastromartins** [comment]
Okay, found the issue.
It's actually this line: https://github.com/nashwaan/xml-js/blob/master/lib/xml2js.js#L104
It must be: `attributes[attribute[1]] = attribute[2] || attributes[3] || attributes[4];` to fetch the value from either of the capturing patterns. You were currently only fetching from the first capturing patters (which is the double quotes).

I'll submit a PR shortly with a simpler way of doing the parsing, I had actually expressed myself poorly previously; I'll show you what I meant.

**Comment by nunocastromartins** [comment]
Ignore the latest push, it was just me experimenting with fixing the commit message where I forgot to close the parenthesis. :-)

Just to know, will you publish to npm anytime soon?

**Comment by nashwaan** [comment]
I merged your pull request because it passed the tests, and then revert it based on your last comment.

Yes, I was planning to release a fix release to npm shortly after the merge.

So, are going to submit another pull request?

**Comment by nunocastromartins** [comment]
Ah, gosh, you didn't have to do that, I deleted my fork already!
It was just a typo in the commit message, and since I had never tried to fix one after submitting a PR I wondered what would happen.

Sorry about that!

**Comment by nunocastromartins** [comment]
You can revert the revert if you don't mind a tiny typo (forgot to close parenthesis) in your git history.

**Comment by nashwaan** [comment]
I hate git system as I never managed to understand how the pull/push/merge/branches work. I expect something, and then something else actually happens.
Today, I just hate it more. Near infinity.

But I somehow managed to release it to npm as `v1.5.2`.

Thanks for your contribution.

**Comment by nunocastromartins** [comment]
I get you, I chuckled at the "Revert Revert"!

Thank you for your quick handling of stuff (and overall useful project)!
