### ISSUE TITLE
Can't convert from JSON to  XML

### ISSUE THREAD

**Issue by Nehaw149** [nashwaan/xml-js#38]
Hello Please let me know of any changes in the configurations or options of the module.

It is not able to convert back the file of JSON to XML.

**Comment by nashwaan** [comment]
Can you provide an example of the code and json file that you tried to convert?
Please try to make it as minimal as possible.

**Comment by Nehaw149** [comment]
Hi Nashwaan,
Below is the required info, 

`var json = fs.readFileSync('./Parsed_XAML.json', 'utf8');
var options = {ignoreComment: true, spaces: 4};
var result = convert.json2xml(json, options);
console.log(result);`

and JSON is

`{
    "Window": {
        "_attributes": {
            "x:Class": "WpfTutorialSamples.Panels.DockPanel",
            "xmlns": "http://schemas.microsoft.com/winfx/2006/xaml/presentation",
            "xmlns:x": "http://schemas.microsoft.com/winfx/2006/xaml",
            "Title": "DockPanel",
            "Height": "250",
            "Width": "250"
        },
        "DockPanel": {
            "Button": [
                {
                    "_attributes": {
                        "DockPanel.Dock": "Left"
                    },
                    "formattedJSON": "Left"
                },
                {
                    "_attributes": {
                        "DockPanel.Dock": "Top"
                    },
                    "_text": "Top"
                },
                {
                    "_attributes": {
                        "DockPanel.Dock": "Right"
                    },
                    "_text": "Right"
                },
                {
                    "_attributes": {
                        "DockPanel.Dock": "Bottom"
                    },
                    "_text": "Bottom"
                },
                {
                    "_text": "Center"
                }
            ]
        }
    }
}`

please let me know.

**Comment by nashwaan** [comment]
@Nehaw149 
You need to pass `compact: true` in the options; because you originally converted the xml to json using compact mode.

Therefore, change to this:
`var options = {ignoreComment: true, spaces: 4, compact: true};`

**Comment by Nehaw149** [comment]
@nashwaan 
In all cases it provides an error saying, Unexpected token < in JSON at position 0. This is observed for all basic JSON objects too.
e.g. var json = {"a":{"b":{}}};

**Comment by Nehaw149** [comment]
Closing the bug as error above is caused due to presence  of data in the generated file.
Thanks for quick help.
