### ISSUE TITLE
Add Typescript 2.0 definition to DefinitelyTyped 

### ISSUE THREAD

**Issue by DenisCarriere** [nashwaan/xml-js#4]
I haven't tried all of the XML libraries, but this is by far the best one I've seen.

I'd like to add a Typescript definition to this project, it will take me a while before understanding your top level schema, but so far it's very clean!

Adding JSDocs to the functions really help out as well.

There's two approaches:
1. Convert project into Typescript (it's a lot of work)
2. Add definitions to http://definitelytyped.org/ (Just need to add the schema of the project, *less work)

Once I get something up and running, I'd like for you @nashwaan to review it, Typescript definitions are pretty straightforward.

I've written a few before, have a look at these examples:

https://gist.github.com/DenisCarriere/11415dc23d5cab134180e86c07f06ae3

**Comment by DenisCarriere** [comment]
Added the typing to DT, this should be available on `npm` within a week or so.

```
npm install @types/xml-js
```

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12369

**Comment by DenisCarriere** [comment]
Perfect, DT has accepted the PR.
The Typescript definition will be on npm as `@types/xml-js`, takes a few days before it's live, I'll send a PR to update your README.md
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12433

**Comment by corbinu** [comment]
@DenisCarriere You can also simply add the types directly to this repo. For example vue is not written in Typescript but as the definition files in the same repo https://github.com/vuejs/vue

**Comment by DenisCarriere** [comment]
Yep I will do that now, I also like having feedback from the DT team, I'll send a pull request

**Comment by DenisCarriere** [comment]
@corbinu Thanks for the reference, that's a really well made typings repo 👍
