### ISSUE TITLE
How insert parent tag for convert from json to xml?

### ISSUE THREAD

**Issue by SergeyAlexsandrovich** [nashwaan/xml-js#44]
Hello!
I have a array objects. 
```
[ { type: 'element', name: 'material', elements: [ [Object] ] },
  { type: 'element', name: 'material', elements: [ [Object] ] },
  { type: 'element', name: 'material', elements: [ [Object] ] },
  { type: 'element', name: 'material', elements: [ [Object] ] },
  { type: 'element', name: 'material', elements: [ [Object] ] } ]
```
And after convert I getting the next xml
```
<material><mattext><p><font size="14"><strong>....</material>
<material><mattext><p><font size="14"><strong>....</material>
```
But if execute `xml2json` for result above then, I receive the error.
Error: Text data outside of root node.
Line: 248
Column: 26
Could you tell me how I can insert root node ?

**Comment by nashwaan** [comment]
hi @SergeyAlexsandrovich ,

In order for me to reproduce the error, I need a complete sample input. Both sample inputs that you provided are not complete.

Please provide a complete sample input that causes this error and try to make it minimal (if possible).

**Comment by nashwaan** [comment]
Closed as no further comments received.
Will re-open if you are still facing this issue.
