### ISSUE TITLE
Allow mapped value to be `undefined` in type for `_attributes`

### ISSUE THREAD

**Issue by edzis** [nashwaan/xml-js#47]
I am extending `ElementCompact` and want to add some explicit optional properties:

	export interface MyElement extends ElementCompact {
	  _attributes: {
	    id: string
	    doIEvenExist?: 'yes' | 'no'
	  }
	}
Unfortunately with this I get TS error:
```
Property 'doIEvenExist' is incompatible with index signature.
  Type '"yes" | "no" | undefined' is not assignable to type 'string | number'.
    Type 'undefined' is not assignable to type 'string | number'.
```

I currently use the following workaround:

    ...
    _attributes: ElementCompact['_attributes'] & {
    ...

**Comment by nashwaan** [comment]
Suggested code was accepted and merged.
