### ISSUE TITLE
Minor: get rid of backslash double quotes

### ISSUE THREAD

**Issue by Opariti** [nashwaan/xml-js#51]
This is not a functional error but the published format can be improved:

The input XML string:

`<?xml version="1.0" encoding="utf-8" ?><l key="license_number_1">  <s id="Pharma HK Central" ip="xxxxxx0" port="yyyyyy0"/>  <s id="Pharma Paris" ip="xxxxxx1" port="yyyyyy1"/>  <s id="Ph Bogota" ip="xxxxxx2" port="yyyyyy2"/></l>`

The xml to JSON code:

```
let options = {
        compact: true,
        trim: true,
        ignoreDeclaration: true,
        ignoreComment: true,
        alwaysChildren: false,
        attributesKey: "$att",
        textKey: "$val"
    };
   let jsonObj = xml_js.xml2json(xmlString, options);
   console.log(JSON.stringify(jsonObj));
```
Conversion output:

"{\"l\":{\"$att\":{\"key\":\"license_number_1\"},\"s\":[{\"$att\":{\"id\":\"Pharma HK Central\",\"ip\":\"xxxxxx0\",\"port\":\"yyyyyy0\"}},{\"$att\":{\"id\":\"Pharma Paris\",\"ip\":\"xxxxxx1\",\"port\":\"yyyyyy1\"}},{\"$att\":{\"id\":\"Ph Bogota\",\"ip\":\"xxxxxx2\",\"port\":\"yyyyyy2\"}}]}}"

Expected:

{"l":{"$att":{"key":"license_number_1"},"s":[{"$att":{"id":"Pharma HK Central","ip":"xxxxxx0","port":"yyyyyy0"}},{"$att":{"id":"Pharma Paris","ip":"xxxxxx1","port":"yyyyyy1"}},{"$att":{"id":"Ph Bogota","ip":"xxxxxx2","port":"yyyyyy2"}}]}}

Of course, the backslah before double quotes make sense because of the output string's leading and trailing double quotes, and, again, it doesn't affect the correct use of the JSON object.
But it would be more readable to have the clean output, other alike packages, less functional than 'xml-js' do it.

**Comment by nashwaan** [comment]
@Opariti 
Sorry for late reply.
To get the desired output, this library already supports your use case. Just use `xml2js()` instead of `xml2json()` in your code.

Therefore, modifying your example, the xml to JSON code should be:
```js
let xml_js = require('xml-js');
let xmlString = '<?xml version="1.0" encoding="utf-8" ?><l key="license_number_1"> <s id="Pharma HK Central" ip="xxxxxx0" port="yyyyyy0"/> <s id="Pharma Paris" ip="xxxxxx1" port="yyyyyy1"/> <s id="Ph Bogota" ip="xxxxxx2" port="yyyyyy2"/></l>';
let options = {
    compact: true,
    trim: true,
    ignoreDeclaration: true,
    ignoreComment: true,
    alwaysChildren: false,
    attributesKey: "$att",
    textKey: "$val"
};
let jsonObj = xml_js.xml2js(xmlString, options);   // <---- use .xml2js() instead of .xml2json()
console.log(JSON.stringify(jsonObj));
```

**Comment by nashwaan** [comment]
Closed as no further comments received.
Will re-open if you are still facing this issue.
