### ISSUE TITLE
Unexpected token when parsing XML to JSON

### ISSUE THREAD

**Issue by oscarsr96** [nashwaan/xml-js#52]
Hi, I'm trying to get a Json from an XML file.

It works with the given XML code:

var xml =
'<?xml version="1.0" encoding="utf-8"?>' +
'<note importance="high" logged="true">' +
'    <title>Happy</title>' +
'    <todo>Work</todo>' +
'    <todo>Play</todo>' +
'</note>';

But it doesn't with my local xml file

 var xml = require('./pregunta.xml')

This is the content:

<?xml version="1.0" encoding="UTF-8"?>
<quiz>
  <question type="category">
    <category>
      <text>Moodle QUIZ XML export</text>
    </category>
  </question>
  <question type="truefalse">
    <name>
      <text>­Si un coche circula a 25m/s...</text>
    </name>
    <questiontext>
      <text>­Lo hace a 90km/h</text>
    </questiontext>
    <answer fraction="100">
      <text>true</text>
    </answer>
    <answer fraction="0">
      <text>false</text>
    </answer>
  </question>
  <question type="truefalse">
    <name>
      <text>­Si un coche circula a 25m/s...</text>
    </name>
    <questiontext>
      <text>­Lo hace a 50m/min</text>
    </questiontext>
    <answer fraction="0">
      <text>true</text>
    </answer>
    <answer fraction="100">
      <text>false</text>
    </answer>
  </question>
  <question type="truefalse">
    <name>
      <text>­Si un coche circula a 25m/s...</text>
    </name>
    <questiontext>
      <text>­Lo hace a 80km/h</text>
    </questiontext>
    <answer fraction="0">
      <text>true</text>
    </answer>
    <answer fraction="100">
      <text>false</text>
    </answer>
  </question>
</quiz>

I get the following error:

Error: Module parse failed: Unexpected token (1:0)
 You may need an appropriate loader to handle this file type. 
| <?xml version="1.0" encoding="UTF-8"?> 
| <quiz>
 | <question type="category">

Could you please help me?
Thanks.

**Comment by luisfronquillo** [comment]
You must load you file this way:
var fs =require("fs"); 
var xml= fs.readFileSync("xmlsample.xml");

i think only '.json' files are able to load through 'require'.

**Comment by nashwaan** [comment]
@oscarsr96 , this is not an issue with this library. The way you tried to load xml file was incorrect.
Use the method suggested by @luisfronquillo .
