### ISSUE TITLE
Convert XML->JSON->XML

### ISSUE THREAD

**Issue by trssssrt** [nashwaan/xml-js#55]
Hey,

I apologize if this is posted in the wrong place, but looking at the Quick Start example we have

```
var convert = require('xml-js');
            var xml =
                '<?xml version="1.0" encoding="utf-8"?>' +
                '<note importance="high" logged="true">' +
                '    <title>Happy</title>' +
                '    <todo>Work</todo>' +
                '    <todo>Play</todo>' +
                '</note>';
            var op = { compact: true, spaces: 4 };
            var result1 = convert.xml2json(xml, op);
            console.log(result1);
```

Converting back,

---
            console.log(convert. json2xml(result1, op));
---

Which gives the following error:

```
json2xml.js:4 Uncaught ReferenceError: Buffer is not defined
```

Other than what's up there, I grabbed xml-js through
````
npm install --save xml-js
````

Thoughts?

**Comment by nashwaan** [comment]
@trssssrt , Sorry for late reply.

I tried to reproduce the issue using your code, but everything went ok.
Here is the code I used:
```js
var convert = require('xml-js');
var xml =
    '<?xml version="1.0" encoding="utf-8"?>' +
    '<note importance="high" logged="true">' +
    '    <title>Happy</title>' +
    '    <todo>Work</todo>' +
    '    <todo>Play</todo>' +
    '</note>';
var op = { compact: true, spaces: 4 };
var result1 = convert.xml2json(xml, op);
console.log(result1);
console.log(convert.json2xml(result1, op));
```
So I am not sure what happened in your end.
By the way, the `xml-js` version I tested is `1.6.2`.

**Comment by nashwaan** [comment]
Closed as no further comments received.
Will re-open if you are still facing this issue here.

**Comment by ravirangappa** [comment]
I have the same issue with Buffer reference in line 4 of the file json2xml.js:

`if (json instanceof Buffer) `

The stack trace:

```
ERROR ReferenceError: Buffer is not defined
    at push../node_modules/xml-js/lib/json2xml.js.module.exports (json2xml.js:4)
```

I believe this is with migration to Node 12.x version. Can you please try it with that version for reproducing it?

Update:

This issue has currently been resolved by the workaround mentioned here:
https://stackoverflow.com/questions/50371593/angular-6-uncaught-referenceerror-buffer-is-not-defined/50377270#50377270

**Comment by krishna-404** [comment]
> This issue has currently been resolved by the workaround mentioned here: [stackoverflow.com/questions/50371593/angular-6-uncaught-referenceerror-buffer-is-not-defined/50377270#50377270](https://stackoverflow.com/questions/50371593/angular-6-uncaught-referenceerror-buffer-is-not-defined/50377270#50377270)

Thank you for this.
