### ISSUE TITLE
The fullTagEmptyElement options is not working 

### ISSUE THREAD

**Issue by abdoolly** [nashwaan/xml-js#59]
making the fullTagEmptyElement in the options either true or false does not matter the tag always come abbreviated.

**Comment by nashwaan** [comment]
@abdoolly Sorry for late reply.

Can you provide a brief example so I can reproduce the issue and fix it.

**Comment by Cy-Tek** [comment]
I am also having this issue. Here is a quick sample that should help. Nothing changes regardless of whether `fullTagEmptyElement` is set to true or false.

```javascript
var test = {
    "textless": {
      calling_offer_code: '',
      mailing_code: '',
      vcpi: '' },
  };

  var options = { compact : true, ignoreComment : true, spaces : 2, fullTagEmptyElement: false};
  console.log(convert.json2xml(test, options));
```

Expected:
```xml
<textless>
	<calling_offer_code/>
	<mailing_code/>
	<vcpi/>
</textless>
```

Actual:
```xml
<textless>
	<calling_offer_code></calling_offer_code>
	<mailing_code></mailing_code>
	<vcpi></vcpi>
</textless>
```

**Comment by nashwaan** [comment]
Actually, the input should be:
```js
var test = {
    "textless": {
      calling_offer_code: {},
      mailing_code: {},
      vcpi: {} },
  };
```

Not:
```js
var test = {
    "textless": {
      calling_offer_code: '',
      mailing_code: '',
      vcpi: '' },
  };
```

Nevertheless, I have updated the package to v1.6.9 to parse your input and produce the result as you expected.

Thanks for providing a clear example.

**Comment by nashwaan** [comment]
Closing this issue as no further feedback received. Will reopen if the issue still persists.
