### ISSUE TITLE
Removing unwanted XML tag names.

### ISSUE THREAD

**Issue by emirselvi** [nashwaan/xml-js#89]
Hello everyone,

In my native app I'm fetching XML data with axios. I can successfully change data to json with xml-js but the json data in this form.
```
{
  "SOAP-ENV:Envelope" : {
     "SOAP-ENV:Body": {
       "ns:anotherTitle": ...
    }
  }
} 
```
I want to remove SOAP-ENV and ns: for better json structure. How can I achieve this? 
Thanks for your help.

**Comment by nashwaan** [comment]
You can pass special function to the `elementNameFn` option to do custom work on the xml element name.

Something like this might solve your problem (not tested):
```js
var convert = require('xml-js');
var xml = '<SOAP-ENV:Envelope>Hi</SOAP-ENV:Envelope>';
var options = {ignoreComment: true, elementNameFn: function(val) {return val.replace('SOAP-ENV:','').replace('ns:','');};
// or simpler: 
// var options = {ignoreComment: true, elementNameFn: val => val.replace('SOAP-ENV:','').replace('ns:','')};
var result = convert.xml2js(xml, options); // or convert.xml2json(xml, options)
console.log(result);
```

You can find more info here  [Options for Custom Processing Functions](https://github.com/nashwaan/xml-js#options-for-custom-processing-functions)

**Comment by emirselvi** [comment]
@nashwaan Thanks for your contribution. It's exactly the same how I want it.
