### ISSUE TITLE
Keep up the great work!

### ISSUE THREAD

**Issue by DenisCarriere** [nashwaan/xml-js#9]
👍 I've been using this library extensively without any issues! Great job!

@nashwaan close this issue when you've read this 🤓

**Comment by nashwaan** [comment]
Your comment just made my day!
😄

**Comment by JulianKingman** [comment]
Went through 5-6 other libraries that were needlessly complicated, poorly documented, and broken. Thanks for a great package!

**Comment by DenisCarriere** [comment]
👍

**Comment by nashwaan** [comment]
I wonder if any of you can help to improve the documentation of this library (README.md file).

I appreciate if you can revise the English as English is not my first language.

Also, suggestions or improvements on the examples are also welcomed.

**Comment by DenisCarriere** [comment]
❤️ Still loving this library, I'm doing the reverse now `xml2json` and everything seems to be working just fine! 👍

**Comment by winniehell** [comment]
I agree, thank you @nashwaan for this great library. It saved me a lot of time and headache. :smiley:
