### ISSUE TITLE
422 Vulnerabilities found, most of which can be fixed easily without breaking any tests

### ISSUE THREAD

**Issue by Zephilim** [nashwaan/xml-js#96]
I am planning on using this lib for a new project of mine and am just doing a little investigation before doing so. Its great to see that there are in excess of 2000 tests. However, after having completed an npm install, I found 422 vulnerabilities, most of which can be fixed easily within seconds, so why not fix them?

running:
> npm audit fix

reduces the vulnerability count right down to 3 low severity vulnerabilities (which can probably also be easily fixed but I haven't investigated those yet), and doing so breaks non of the tests.

**Comment by nashwaan** [comment]
@Zephilim Thanks for this tip. I ran `npm audit fix` and I things most of the issues are fixed.
I will publish this in the coming few days as I plan to update the Readme a little. Stay tuned.

**Comment by Zephilim** [comment]
Hey nashwaan, that's great, thanks for that. I will now unfork (just delete my fork!) your project.

**Comment by nashwaan** [comment]
@Zephilim Sorry for the delay. This is now published in v1.6.10.

**Comment by Zephilim** [comment]
Excellent, thanks
